apiVersion: v1
kind: Namespace
metadata:
  name: dui
  environment: staging
  purpose: dui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dui-go-client
  namespace: dui
  labels:
    app: dui
    distribution: client
    language: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dui
      distribution: client
      language: go
  template:
    metadata:
      labels:
        app: dui
        distribution: client
        language: go
    spec:
      containers:
      - name: master
        image: caladreas/dui-go-client:0.1.1
        env:
        - name: MEMBERSHIP_UPDATE_RATE_IN_MILLIS
          value: "2500"
        ports:
        - name: external
          containerPort: 7777