package feiwu

const (
	FEIWU_HEADER_BYTE_MARKLER       = 0x08
	HEADER_SIZE_FEIWU               = 2
	HEADER_SIZE_MESSAGE_TYPE        = 2
	HEADER_SIZE_MESSAGE_ORIGIN_SIZE = 4
	HEADER_SIZE_MESSAGE_SIZE        = 4
	HEADER_SIZE_MESSAGE_DIGEST      = 32
	MEMBERSHIP_NETWORK              = "udp"
	MEMBERSHUP_GROUP_ADDRESS        = "230.0.0.0:7791"
)
